# -*- coding: utf-8 -*

USERKEY = "userkey"

# DB Attr Key_value
CARBRAND = "CARBRAND"
CARNAME = "CARNAME"
CARMODEL = "CARMODEL"
PRICE = "PRICE"
TYPE = "TYPE"
SEATS = "SEATS"

# dialog key
SEARCHFIN = "SEARCHFIN"
QUERYFIN = "QUERYFIN"
MULTIKEY = "MULTIKEY"
CARNUM = "CARNUM"
MULTIRESULT = "MULTIRESULT"

DIALOG = {
    CARBRAND: "ASK CARBRAND",
    CARNAME: "ASK CARNAME",
    CARMODEL: "ASK CARMODEL",
    PRICE: "ASK PRICE",
    TYPE: "ASK TYPE",
    SEATS: "ASK SEATS",
    SEARCHFIN: "SEARCH FIN",
    QUERYFIN: "QUERY FIN [KEY * VALUE *]",
    MULTIKEY: "MULTIKEY *",
    CARNUM: "CARNUM *",
    MULTIRESULT: "MULTIRESULT MODEL * KEY * VALUE *"
}

UTIMAXPRICE = 65535

ARGORDER = [[u"CARBRAND", u"CARNAME", u"CARMODEL", u"PRICE", u"TYPE", u"SEATS"],
            [u"PRICE", u"TYPE", u"SEATS", u"CARBRAND", u"CARNAME", u"CARMODEL", ]]

