# -*- coding: utf-8 -*

USERKEY = "userkey"

# DB Attr Key_value
CARBRAND = "CARBRAND"
CARNAME = "CARNAME"
CARMODEL = "CARMODEL"
PRICE = "PRICE"
TYPE = "TYPE"
SEATS = "SEATS"

# dialog key
SEARCHFIN = "SEARCHFIN"
QUERYFIN = "QUERYFIN"
QUERYFINMULTI = "QUERYFINMULTI"

DIALOG = {
    CARBRAND: "ASK CARBRAND",
    CARNAME: "ASK CARNAME",
    CARMODEL: "ASK CARMODEL",
    PRICE: "ASK PRICE",
    TYPE: "ASK TYPE",
    SEATS: "ASK SEATS",
    SEARCHFIN: "SEARCH FIN",
    QUERYFIN: "QUERY FIN KEY * VALUE *",
    QUERYFINMULTI: "QUERY FIN MULTI",
}

UTIMAXPRICE = 65535

ARGORDER = [[u"CARBRAND", u"CARNAME", u"CARMODEL", u"PRICE", u"TYPE", u"SEATS"],
            [u"PRICE", u"TYPE", u"SEATS", u"CARBRAND", u"CARNAME", u"CARMODEL", ]]

